s-generator:
  config:
    temp-file-prefix: SGVideo
    video-format: mp4
    video-codec-name: H264
    frame-rate: 24

  subtitles-generation:
    font-size: 12
    font-color:
      r: 200
      g: 200
      b: 200
    default-font-name: Arial
    bottom-margin: 50

spring:
  application:
    name: subtitles-generator

  # PostgreSQL settings
  datasource:
    url: jdbc:postgresql://localhost:5432/sgapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # H2 settings
  h2:
    datasource:
      url: jdbc:h2:mem:sgapp
      username: sa
      password: password
      driver-class-name: org.h2.Driver
    console:
      enabled: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html